### ISSUE TITLE
תמונות של חכ״ים

### ISSUE THREAD

**Issue by Amitasulin9** [shenkarlab/Off-The-record#16]
@shaulams  @mushon 
היי שאול 
תשלח לנו בבקשה את כל התמונות (צרובות) של החכ״ים 
במידהוזה קובץ גדול אפשר להעביר אותו ב
wetransfer.com 

amitproject98@gmail.com
benzvi449@gmail.com
eldadtza@gmail.com

תודה

**Comment by shaulams** [comment]
הי חברים
סיכמנו שנעשה הפוך
אני צריך מכם רשימה של החכים שאתם צריכים
אתם הרי לא משתמשים בכולם אם אני לא טועה
ואני כבר אשלח לכם צריבות בהתאם

הולך?

**Comment by Amitasulin9** [comment]
מושון רוצה שנכניס את כולם

**Comment by shaulams** [comment]
מושון רוצה שנכניס את כולם
הבנתי
אוקי, אני שולח מייל למערכת
תודה
