### ISSUE TITLE
Write a Python script to fit Nir's required format

### ISSUE THREAD

**Issue by mushon** [shenkarlab/Off-The-record#18]
As far as I understand this would be following the אאא, אאב, אאג… format but merged for all politicians and not divided (the divided version might still be needed but is not sufficient on its own). @nir-jackson please confirm.

**Comment by nir-jackson** [comment]
Adam @akariv said we can use my c#. if thats the case i see no reason for alex to do it in python. i just want him to concentrate on getting what he already made to work properly.

**Comment by mushon** [comment]
@nir-jackson I would like to remind you that this C# script would need to run regularly and would complicate your setup. I think it would be much more robust and healthy if you stick to Python and don't patch things up. Especially since this part is quite straight forward.

**Comment by nir-jackson** [comment]
i guess so, 
i'll send in by mail an example of the structure of the json after their merge.

**Comment by mushon** [comment]
Hi @AlexGr2 & @nir-jackson,
I understand from @eldadtzadok that this issue should be pretty much there, as the python code has been written. Alex, please confirm this is indeed the case and whether you were able to run the script and merge the files. If this works we would like to proceed with uploading it to the server while Alex is working on issue #19 (JSON regular updates). We would like to have the site working on the Calcalist server today even before Alex finishes the update code. We'd rather check what we have right now as soon as possible as I just talked with Shaul from Calcalist and this project is due for launch on Thursday.

@AlexGr2 please update us both on this issue and on issue #19 and let us know if you need any help or feedback and when can we expect to get some more code and data from you.

Thanks (we're almost there),
Mushon

**Comment by nir-jackson** [comment]
we've uploaded 3 python scripts to github
1. MainScript.py - the main script to create the JSON files needed.
2. ThreeLetterListGather.py - merges the seperate search files.
3. realTimeUpdate.py - updates the JSON files regularly.

i've asked alex to send me a READ me file to explain how to get them to work.

alex is mostly available via email. he is not familiar with the github interface.
if you have any questions and you can't reach him contact me.

**Comment by AlexGr2** [comment]
סקיפטים חדשים שניר מעלה, שכתבו לגמרי, אם יש איזה דאטא שנוצרה על ידי סקריפט
הישן הוא לא רלוונטי כבר.

**Comment by akariv** [comment]
Which repository are you updating?
https://github.com/shenkarlab/Off-The-record
or
https://github.com/nir-jackson/Off-The-record

@nir-jackson

**Comment by nir-jackson** [comment]
https://github.com/shenkarlab/Off-The-record

the scripts are under the folder "Scripts"
the website is under the folder "WebSite"

call me before you upload the website to the server. 
do you know what our domain is yet? (if there is one i'm not sure if that's how it works)

**Comment by akariv** [comment]
Still waiting for the README

**Comment by mushon** [comment]
@nir-jackson were you able to run the script and get the data you need? Can you document the installation of the project in the README? (issue #20)

@AlexGr2 are you working on issue #19? Would you please upload your code so we can review and assist if necessary?

**Comment by AlexGr2** [comment]
everything is uploaded, I'm writing readme

**Comment by nir-jackson** [comment]
i never knew how to run the python script. i always received the json's after they were already made. all  the know how of how to run the scripts alex knows. all i need to know is the location of the json's that it creates.

**Comment by nir-jackson** [comment]
i've just uploaded the readme.txt

**Comment by akariv** [comment]
@nir-jackson @AlexGr2 
Thanks, but in the readme I need step-by-step instructions for setting up your environment: which scripts to run, in which order, which input files should be there, where the output files will be etc.
Right now it's more of a documentation of the scripts' implementation which is interesting but not what I need.

**Comment by akariv** [comment]
Oh,  and Alex - Please revise the code so that it uses relative paths and not absolute. 
Also use os.path.join() for cross platform path concatenation,  instead of using backslashes directly.

**Comment by AlexGr2** [comment]
Please show me and example of using :
Also use os.path.join() for cross platform path concatenation, instead of
using backslashes directly.

**Comment by AlexGr2** [comment]
Please show me and example of using : os.path.join()

**Comment by nir-jackson** [comment]
we've just uploaded the new readme.

**Comment by nir-jackson** [comment]
@akariv 

we've uploaded the scripts again after changing the path to relative paths

**Comment by nir-jackson** [comment]
hey, @akariv @mushon 

has there been any progress? is the script working? when do you think we can get the site up?

**Comment by akariv** [comment]
You can find the data here (sample URLs):
http://viz.calcalist.co.il/otr/data/pythonFiles/אות.txt
http://viz.calcalist.co.il/otr/data/wordAllCount/Netanyahu.txt
http://viz.calcalist.co.il/otr/data/WholeDates/Netanyahu.txt
http://viz.calcalist.co.il/otr/data/WCheckedList/SahbekimCountRecords.txt

once your website code is revised and pushed please let me know.

**Comment by nir-jackson** [comment]
good morning!
the website is ready. just upload it under the same domain name.
@akariv @mushon

**Comment by nir-jackson** [comment]
BTW, i i think you are missing information on the "WholeDates".
according to what you sent me Netanyahu only talked during this month, where is the rest of the information?
@akariv

**Comment by AlexGr2** [comment]
Adam, in the MainScript.py, please check these lines of code are
uncommented,  this is recursive feed for all page data

# getTargetIds(data["posts"]["paging"]["next"], list_NextUrls)
#
# for url in list_NextUrls:
#    buildString += createBuffer_Next(url)

**Comment by AlexGr2** [comment]
Without these lines you get only the first page of posts.

**Comment by akariv** [comment]
@AlexGr2 
1. please uncomment these lines and update github
2. you still have non-portable paths (e.g. look for "\potilics.txt" which is windows only)

**Comment by nir-jackson** [comment]
@akariv @AlexGr2  I've commented the lines specified in the script MainScript.py
Tell me ounce you uploaded the site i want to run tests on it.

**Comment by nir-jackson** [comment]
@akariv  @AlexGr2  We've just re uploaded the scripts. please run it again with the new scripts.

**Comment by akariv** [comment]
http://viz.calcalist.co.il/otr/web/

@mushon @nir-jackson

**Comment by nir-jackson** [comment]
some search files were not created (סתם.txt קטן.txt) i looked at the script responsible (ThreeLetterListGather.py) and saw the reason and fixed it. i need you to run ThreeLetterListGather.py again.

@akariv

**Comment by akariv** [comment]
done

**Comment by nir-jackson** [comment]
thanks that fixed it :) now i have quite a lot of bugs to fix and i'm going to need simple access to the website files so i can update the with minor changes without needing to tell you to update them.
how can i upload new files to the server? can you provide me with a FTP account or something?

@akariv  @mushon

**Comment by akariv** [comment]
debugging with the production server is not a good practice, you should be
able to test on your own machine.

I suggest you test the website locally with the data in the server (or your
local version).
when your fixes are done I'll upload the website.

**Comment by nir-jackson** [comment]
i'm having (and always have been) trouble loading JSON that is not under the same domain as the site. i was able to load "kikars" json by adding this to the ajax call:
$.ajax({
			crossDomain: true,
			url: domain + 'WholeDates/'+ v.id +'.txt',
			dataType: 'jsonp',
			type: 'get',


but its not working for the json on our server. do you know of a solution?

@akariv

**Comment by mushon** [comment]
@nir-Jackson Is that still the case now after the changes you made to the URL formats?

Mushon Zer-Aviv
Mushon.com | Shual.com | @Mushon

**Comment by nir-jackson** [comment]
yep, only on me machine.....

**Comment by akariv** [comment]
you can download all data and use it locally from here:
http://viz.calcalist.co.il/otr/data/out.zip

**Comment by nir-jackson** [comment]
Thanks!! :)

**Comment by nir-jackson** [comment]
i'm closing this issue, we got the site running and the issue in the title (of this issue) has been resolved
