### ISSUE TITLE
Optimize JSON regular updates 

### ISSUE THREAD

**Issue by mushon** [shenkarlab/Off-The-record#19]
Right now the JSON generation takes an unacceptable time to update, this is due to its poor optimization. The script should not recalculate everything again and again but update only the files than need update, that would mean that it would run every 5 or 10 minutes and look only for new posts, these posts would be analyzed and would be added to the relevant existing JSON files. Such a process will be much faster and much less time consuming than what is running right now. @nir-jackson please confirm. @AlexGr2 this is on you.

**Comment by nir-jackson** [comment]
confirm

**Comment by nir-jackson** [comment]
@AlexGr2 @akariv Has this issue been resolved?

**Comment by AlexGr2** [comment]
realTimeUpdate.py script responsible for the live updates, hence the name

**Comment by nir-jackson** [comment]
i'm closing this issue.
@mushon
