### ISSUE TITLE
Quotes of MPs should link to the original status updates in Facebook

### ISSUE THREAD

**Issue by mushon** [shenkarlab/Off-The-record#22]
That's quite essential actually.

**Comment by nir-jackson** [comment]
done (only need designers to look at it and tell me how it should look)
@Amitasulin9 @mushon @eldadtzadok

**Comment by mushon** [comment]
Please upload it to the gh-pages branch so we can see what you've done. It should appear here:
http://shenkarlab.github.io/Off-The-record/

**Comment by nir-jackson** [comment]
done (including in the lower part)
