### ISSUE TITLE
MPs repeat themselves in results + non-candidates still appear

### ISSUE THREAD

**Issue by mushon** [shenkarlab/Off-The-record#23]
Search: מאבק
How much of Danu Danon can one really stand?

![screen shot 2015-03-04 at 11 45 05](https://cloud.githubusercontent.com/assets/27123/6481180/017f6fda-c264-11e4-8535-4a077a99043d.png)

**Comment by shaulams** [comment]
צחקתי בקול רם

**Comment by nir-jackson** [comment]
@AlexGr2 please remove 66398526339 from your politicians list. he is not relevant anymore.

**Comment by AlexGr2** [comment]
done

**Comment by nir-jackson** [comment]
By removing 66398526339 (Nitzan Horowitz) from the list, the bug has been fixed.
all that needs to be done is delete all the files/folders that are called 66398526339.

@akariv  @mushon

**Comment by nir-jackson** [comment]
after a lot of testing i can say that i haven't encountered this bug again and i declare it fixed.
tell me if you see it again

**Comment by shaulams** [comment]
הי ניר, אני מעלה צילומי מסך
גלעד ארדן עדיין כפול
וגדעון סער עדיין מופיע בלי שם
![2015 03 05 11 45 41](https://cloud.githubusercontent.com/assets/10020924/6502568/5c49955c-c32d-11e4-94bc-112a44b94d4c.png)
![2015 03 05 11 45 30](https://cloud.githubusercontent.com/assets/10020924/6502571/602f35dc-c32d-11e4-9772-dcd422bb4341.png)

**Comment by nir-jackson** [comment]
@mushon @akariv  @AlexGr2 

the problem was that 207139259326193 (gilad ardan) was writen twice in the politics.txt file (the file responsible of all the politicians) and i removed GideonSaarLikud (gidon saar) from the list because he is not relevant anymore.

we need to delete all data that belong to GideonSaarLikud, and there are 2 similar data for 207139259326193 (gilad ardan), so we need to delete one of them. i recommend deleting the entire data and rerunning the scripts with the new politics.txt file.

**Comment by nir-jackson** [comment]
as in most cases the problem is with the data, not the website ;)

**Comment by nir-jackson** [comment]
i've also removed Ofir Akunis who was writen twice

**Comment by nir-jackson** [comment]
לבנתיים אני סוגר את הבעיה הזאת מפי שהיא טופלה.
אם אתם רואים עוד מקרים כאלו תודיעו לי

**Comment by shaulams** [comment]
אני לא יודע איך לבדוק אם זה טופל. כשאני מחפש אני עדיין רואה גלעד ארדן
ואופיר אקוניס כפולים

**Comment by AlexGr2** [comment]
צריך להשתמש בpolitics.txt החדש ולנקות את הדאטא ולהריץ את הסריפט מחדש


2015-03-05 16:28 GMT+02:00 shaulams <notifications@github.com>:

> אני לא יודע איך לבדוק אם זה טופל. כשאני מחפש אני עדיין רואה גלעד ארדן
> ואופיר אקוניס כפולים
>

**Comment by nir-jackson** [comment]
עוד לא עודכן המידע בשרת..... אדם צריך להעלות את הסקריפטים החדשים ואת האתר מחדש.
