### ISSUE TITLE
The 1,2,3 rank numbers in the groups look like item counts

### ISSUE THREAD

**Issue by mushon** [shenkarlab/Off-The-record#24]
This is a misuse of a design pattern as the circular number on the corner of a square/icon is used to mark notifications/item-count and not the rank. I suggest adding the number to the name like: "2. מוטי יוגב " and using the circular red number to indeed show the number of times the candidate used the term in question.

**Comment by mushon** [comment]
@eldadtzadok @moranbz @Amitasulin9 

I mocked up the way I think the numbering should work. This is based on the numbers found after the click. You would see it also exposes a bug in the way the results are ordered. Either way, I know implementing it will be very simple (the data is already there, it is basically a matter of replacing one number with another). While this is not a show stopper I really think it is worth changing, and while you're at it, get rid of the numbers in the groups, they're not needed and are more confusing than informing.
![screen shot 2015-03-06 at 9 22 15 am](https://cloud.githubusercontent.com/assets/27123/6521593/6a0cbf60-c3e2-11e4-816c-ec2ba9e3d8ed.png)

@shaulams your thoughts…

**Comment by moranbz** [comment]
ומה יקרה כשיחפשו מילים יותר נפוצות, ואז המספרים הופכים לתלת ספרתיים?
לדוגמא ״שלום״

**Comment by mushon** [comment]
שלום לסילבן

![screen shot 2015-03-06 at 9 55 26 am](https://cloud.githubusercontent.com/assets/27123/6521977/039348b2-c3e7-11e4-9aba-bdb96586bff4.png)

**Comment by shaulams** [comment]
יש בעיה בסדר של התוצאות?

**Comment by mushon** [comment]
בדקתי שוב ולא היתה בעיה בדפים כמו ״כן״ (מצורף). נתקלתי בבעיה רק בדף של המבקר (מצד שני לא בדקתי בהרבה דפים). אם תטמיעו את השינוי הזה נוכל לוודא:

![screen shot 2015-03-06 at 10 14 11 am](https://cloud.githubusercontent.com/assets/27123/6522307/3627e076-c3ec-11e4-9442-48274a47c650.png)

**Comment by mushon** [comment]
(38)אגב, גיליתי שאלי ישי (64) אומר יותר מרן מאריה דרעי…

**Comment by moranbz** [comment]
לפי התמונה ששלחת כן יש בעיה עם ״כן״ יוני שטבון אמור להיות לפני משה פייגלין

**Comment by mushon** [comment]
וואלה נכון.
צריך לבדוק פשוט שהסידור של הרשימה עושה שימוש באותו מספר אותו אנחנו מציגים בתוצאות החיפוש
@nir-jackson @AlexGr2

**Comment by nir-jackson** [comment]
זה הפתיעה אותי.
אבל סידרתי את זה בלי בעיה :smile_cat: 
לפני שאני מעלה לגיט האב יש עוד דברים שאתם רואים שאני צריך לסדר?

**Comment by moranbz** [comment]
לא סידרת את הפלוס ליד הטיים ליין שיופיע באופן קבוע

**Comment by nir-jackson** [comment]
הסיבה לכך שעוד לא אמרתם לי ב100 אחוז שזה מה שאתם רוצים אז עוד לא עשיתי את זה, 
האם אתם בטוחים אתם רוצים + קבוע ליד השנה?

**Comment by shaulams** [comment]
זה יהיה נחמד

**Comment by nir-jackson** [comment]
אני ממשיך את הדיון הזה ההבעיה מספר #40

**Comment by mushon** [comment]
@nir-jackson
מה שסדרת זה את הסדר של התוצאות?
את המספר שמציג את מספר התוצאות?
גם וגם?

**Comment by nir-jackson** [comment]
גם וגם

**Comment by mushon** [comment]
איזה כיף!!!
אתה מלך אתה!
אם כך תורידו בבקשה את ה1-2-3 מהקבוצות כדי שלא יהיה בלבול בין השניים ויאללה, להגיש!
תגיד לי מתי וארים טלפון לאדם כדי שיכניס את הכל

**Comment by nir-jackson** [comment]
בסדר,
העלתי את השינויים
תגיד לאדם שיעלה את הקוד החדש 
הקבצים שהשתנו הם:
Index.html
FAQ_new.pdf
Top3.js
Visualization.js
timeline.js
@akariv @mushon

**Comment by mushon** [comment]
אוקיי,
אדם עדכן, זה נראה טוב.
תעברו על זה מהר שאין פיקשושים של הרגע האחרון

**Comment by mushon** [comment]
@nir-jackson
תוכל רק להוריד את המספור 1-2-3 מהקבוצות (המיליטנטים,הכלכלנים…)

**Comment by nir-jackson** [comment]
שלא יהיה בכלל מספור?

**Comment by mushon** [comment]
כן

**Comment by nir-jackson** [comment]
הורדתי
והעלתי את הקוד מעודכן

**Comment by mushon** [comment]
יש עוד משהו שאתם רואים או שאפשר להשיק?
@shaulams

**Comment by nir-jackson** [comment]
@mushon @akariv 
ראיתי שהעלתם תודה רבה זה,
רק עשיתי שינוי קטן לindex.html
please upload the latest index

**Comment by moranbz** [comment]
אנה עדכנו כשזה באויר (: 
@shaulams

**Comment by akariv** [comment]
הקבצים העדכניים ביותר באתר.
