### ISSUE TITLE
Word mismatches

### ISSUE THREAD

**Issue by mushon** [shenkarlab/Off-The-record#27]
It seems that words like ``צה״ל`` don't match with words like ``צהל`` even though they are counted together. See:
![screen shot 2015-03-04 at 12 08 16 pm](https://cloud.githubusercontent.com/assets/27123/6481566/56024c3c-c267-11e4-900f-4023c0681a8f.png)

**Comment by AlexGr2** [comment]
כדי לבדוק מילה אני מנקה אותה מכל סימנים פיסוק. כנראה --> '  הוא אחד מהם,
אבטל אותו בבדיקה

**Comment by nir-jackson** [comment]
@AlexGr2 thanks!
even though the word is shown as "צהל" the actual word in the original post was "צה"ל" that's why my system cant find it in the original post so it displays it not in the correct location.

@mushon

**Comment by AlexGr2** [comment]
I will send you updated script

**Comment by nir-jackson** [comment]
fixed!
