### ISSUE TITLE
Acknowledge the candidates that don't have public FB pages

### ISSUE THREAD

**Issue by mushon** [shenkarlab/Off-The-record#30]
We've already discussed this and I know you had a solution for it. Make sure that if you don't acknowledge it everyone would complain that you're tainted and the supporters of MPs like Stav Shaffir will be all over you for no real reason. We don't want that…

**Comment by shaulams** [comment]
@mushon זה כתוב באופן מפורט מאוד בעמוד האודות

**Comment by mushon** [comment]
@shaulams אני בספק אם אנשים יפתחו את עמוד האודות. 
הייתי מציע לתת תוצאות חיפוש לכל המועמדים ולציין בפירוש את אלה שאינם מתחזקים דף פומבי
לכל הפחות הערה כשהחיפוש (סינון) לא נותן תוצאה בסגנון:
![mock](https://cloud.githubusercontent.com/assets/27123/6482421/5e196fc0-c26e-11e4-9d30-270c5d2d0530.png)

@eldadtzadok עצבו את זה לפני שאתם מנחים את ניר להטמיע

**Comment by shaulams** [comment]
@mushon
אה, אוקי. בתכלס זה הגיוני

**Comment by nir-jackson** [comment]
still waiting for a response from the design team before i start implementation
@mushon

**Comment by mushon** [comment]
@shenkarlab/off-the-record please let me know you're on it. @nir-jackson can you ping them on the phone or on WhatsApp?

**Comment by nir-jackson** [comment]
@akariv  @mushon

hey, we've uploaded new scripts (ThreeLetterListGather.py, MainScript.py, potilics.txt, realTimeUpdate.py) please delete all the current data and rerun the scripts (i need you to delete the old data because of unwanted data that needs to be removed from the server).

additional I've updated the the website code. so please re upload the files index.html, style_new_new.css, Visualization.js, Top3.js.

**Comment by nir-jackson** [comment]
התגובה של מורן:


רשמנו ב״איך זה עובד״ מדוע ישנם אנשים שלא מופיעים באתר, להכניס אותם עכשו לאתר רק בשביל לכתוב שאין להם דף 
ציבורי, 
זה גם הרבה עבודה בשביל ניר, וגם מעט מסורבל. זה הרבה אנשים זו לא רק סתו שפיר, ונצטרך להתייחס לסיבות נוספות שבגללם לא נכנסו לאתר, לדוגמא חברי הכנסת הערבים שכותבים בערבית, וחברי הכנסת הרוסים שכותבים ברוסית, חברי הכנסת החרדים שממעטים לכתוב בפייסבוק אם בכלל וכו׳...

**Comment by mushon** [comment]
@nir-jackson please don't comment for @moranbz. I want her to do the commenting.

**Comment by moranbz** [comment]
רשמנו ב״איך זה עובד״ מדוע ישנם אנשים שלא מופיעים באתר, להכניס אותם עכשו לאתר רק בשביל לכתוב שאין להם דף 
ציבורי, 
זה גם הרבה עבודה בשביל ניר, וגם מעט מסורבל. זה הרבה אנשים זו לא רק סתו שפיר, ונצטרך להתייחס לסיבות נוספות שבגללם לא נכנסו לאתר, לדוגמא חברי הכנסת הערבים שכותבים בערבית, וחברי הכנסת הרוסים שכותבים ברוסית, חברי הכנסת החרדים שממעטים לכתוב בפייסבוק אם בכלל וכו׳...

**Comment by mushon** [comment]
Fair enough. Closing.
