### ISSUE TITLE
wrong counting

### ISSUE THREAD

**Issue by shaulams** [shenkarlab/Off-The-record#33]
יש משהו מוזר במסך של הכלכלנים
לא יכול להיות שאלה האנשים שמדברים הכי הרבה על כלכלה
אם תחפשו את המילה תקציב, תקבלו הרבה אנשים אחרים שמדברים הרבה יותר על העניין הזה
וגם, אם תחפשו את המילה עוני תקבלו הרבה יותר אנשים שמדברים עליה מאשר אלאלוף
בקיצור, יש פה טעות
![2015 03 05 11 45 50](https://cloud.githubusercontent.com/assets/10020924/6502588/9215acc0-c32d-11e4-8885-2ccac7d5b615.png)

@nir-jackson @mushon @akariv

**Comment by AlexGr2** [comment]
זה לא מוזר, החיפוש במקרה הזה הוא יחסי, כמות מילים חוזרים על כמות סה'כ
פוסטים.

2015-03-05 11:49 GMT+02:00 shaulams <notifications@github.com>:

**Comment by nir-jackson** [comment]
אין פה טעות.
התוצאות הן באופן יחסי לסה"כ המילים שהם אמרו. 
אם אנחנו עושים את זה נטו לפי כמות תמיד יוצא אותן תוצאות בכל הקטגוריות. ציפי, שלי וזהבה.

מה שאני מציע זה לעשות "רף מינימום" של סה"כ מילים.
כלומר להראות תוצאות של אנשים שאמרו לפחות 50,000 מילים ואז פוליטיקאים שיש להם פייסבוק חדש ולא רלוונטי לא יופיעו

**Comment by mushon** [comment]
רעיון מצויין ניר
@AlexGr2 תעבוד על זה?

**Comment by nir-jackson** [comment]
@mushon 
אני רק זרקתי לאוויר את המספר 50000. 

צריך לבדוק מספר.

@AlexGr2
 תכין בבקשה את הקובץ 
wordsCountRecords.txt 
פשוט שיופיע שם כל הפוליטחקאיפ כדי שנוכל להחליט על מספר.

**Comment by AlexGr2** [comment]
יש לכם אותו הוא נוצר בלי יחסיות

2015-03-05 12:20 GMT+02:00 Nir Jackson <notifications@github.com>:

**Comment by nir-jackson** [comment]
@AlexGr2
אין לנו אותו
אני רוצה לראות לכל פוליטיקאי כמה מילים הוא אמר.

**Comment by AlexGr2** [comment]
תחפשו אותו בתקייה WCheckedList, הוא נוצר עם כל השאר

**Comment by nir-jackson** [comment]
אני לא סתם אומר...... אין לנו אותו... אם יש לך אותו תשלח בבקשה

**Comment by AlexGr2** [comment]
אני צריך להריץ את הסקריפט מהתחלה ואז אשלח לכם

**Comment by nir-jackson** [comment]
ההשארה שלי ל50,000 הייתה די מדוייקת.
אבל אז ראיתי שלמשה כחלון יש 38,000 מילים (כי הוא פתח פייסבוק רק לאחרונה)
לכן אני ממליץ לא לבדוק פוליטיקאים עם פחות מ35,000 מילים

@AlexGr2 אתה יכול לעשות את זה?

**Comment by AlexGr2** [comment]
כן, אעשה את זה עכשיו ואשלח

2015-03-05 16:15 GMT+02:00 Nir Jackson <notifications@github.com>:

**Comment by nir-jackson** [comment]
טופל. רק צריך להריץ את הסקריפטים מחדש ולמחוק את המידע הישן
