### ISSUE TITLE
Add more words to the no-count list

### ISSUE THREAD

**Issue by mushon** [shenkarlab/Off-The-record#35]
I know we have words like "לא" on a list of words to ignore. We need to add more words to it as right now many of the words on the last sections are meaningless. These are words like:
- מה
- כדי
- לי
- אך
- …

I also think it is not very telling when in almost all of their cases the politicians repeating words are their names as they simply sign it on all or most of their posts. I would suggest filtering against their names as well.

@nir-jackson @shaulams @moranbz @eldadtzadok @Amitasulin9 I would love to get your feedback on this too.

**Comment by nir-jackson** [comment]
i don't mind.....

**Comment by shaulams** [comment]
אני בסדר עם מה שמושון הציע

**Comment by nir-jackson** [comment]
#42 מעכשיו אני מרכז את הנושא הזה ב
