### ISSUE TITLE
Add "לפוסט" links to every place where a post is quoted

### ISSUE THREAD

**Issue by mushon** [shenkarlab/Off-The-record#37]
Especially in the last section.
+
Replace the word "לפוסט" with something less prominent. For example ⬅ (``&#11013;``)

**Comment by nir-jackson** [comment]
i've added the links to the posts in the last section. and i've talked to moran to redesign the "לפוסט" text to look better

**Comment by nir-jackson** [comment]
![image](https://cloud.githubusercontent.com/assets/9511653/6503789/f190ccd8-c338-11e4-98cf-4e617b408167.png)

@mushon hows this?

**Comment by mushon** [comment]
I think it's taking too much attention off the content 

Mushon Zer-Aviv
Mushon.com | Shual.com | @Mushon

**Comment by nir-jackson** [comment]
@Amitasulin9 @moranbz @eldadtzadok איך זה נראה?? איך לשנות את זה?

**Comment by eldadtzadok** [comment]
נסה לעשות שני חצים
<<
בצבע כחול

**Comment by nir-jackson** [comment]
איך זה?
![image](https://cloud.githubusercontent.com/assets/9511653/6507997/9006a890-c35e-11e4-9e9b-d2c79d3ed53b.png)

![image](https://cloud.githubusercontent.com/assets/9511653/6508024/b8d5be00-c35e-11e4-8aac-510fea2ec39a.png)

**Comment by mushon** [comment]
לדעתי אפשר להסתפק בחצים ללא כיתוב

**Comment by eldadtzadok** [comment]
מסכים עם מושון (זאת הייתה כוונתי)

**Comment by shaulams** [comment]
גם אני

**Comment by moranbz** [comment]
אני גם בעד >>

**Comment by eldadtzadok** [comment]
וואו בסוף אני עוד אאמין שהפרוייקט יעלה

**Comment by moranbz** [comment]
זה לא החג של הניסים...

**Comment by nir-jackson** [comment]
![image](https://cloud.githubusercontent.com/assets/9511653/6508286/9c3f8fe4-c360-11e4-827f-f11052b32628.png)

**Comment by nir-jackson** [comment]
אני מניח שהשתיקה זה הסכמה. אני סוגר את הבעיה הזאת

**Comment by moranbz** [comment]
נירוש זה מעולה! רק תחזיר את זה להיות בגודל של הפונט

**Comment by mushon** [comment]
כן סבבה
