### ISSUE TITLE
Create a Favicon for the site

### ISSUE THREAD

**Issue by mushon** [shenkarlab/Off-The-record#38]
@Amitasulin9 @eldadtzadok @moranbz

**Comment by moranbz** [comment]
באזיה גודל צריך להיות ה-favicon?

**Comment by mushon** [comment]
16,32,48,57,128px
but starting with 16,32 would be fine.

More:
http://stackoverflow.com/questions/23849377/html-5-favicon-support/23851464#23851464

**Comment by moranbz** [comment]
done (:
שלחתי במייל...

**Comment by mushon** [comment]
תעשי ״דראג-אנד-דרופ״ גם לפה ואז תעשי ״אסיין״ של ה״אישיו״ לניר.
תודה ״נשמה״

**Comment by shaulams** [comment]
אני מתחיל לחבב את הגיטהאב הזה

**Comment by moranbz** [comment]
![favicon 128px](https://cloud.githubusercontent.com/assets/9464025/6505589/6ccbe168-c34c-11e4-8a1c-458b4af82c44.png)
![favicon 57px](https://cloud.githubusercontent.com/assets/9464025/6505596/76b52540-c34c-11e4-9626-2fc6a26a7572.png)
![favicon 48px](https://cloud.githubusercontent.com/assets/9464025/6505604/7a81ba62-c34c-11e4-8e10-4b9bdf8e66f0.png)
![favicon 16px](https://cloud.githubusercontent.com/assets/9464025/6505607/829ae9a8-c34c-11e4-9dc3-137c77ce4fc7.png)
![favicon 32px](https://cloud.githubusercontent.com/assets/9464025/6505608/858f2af2-c34c-11e4-9a6f-981b877481e4.png)

**Comment by nir-jackson** [comment]
Done.

@mushon @akariv tell me when you've uploaded the website
