### ISSUE TITLE
wrong grammar

### ISSUE THREAD

**Issue by shaulams** [shenkarlab/Off-The-record#39]
בכיתובים למטה, כתוב שהנתונים מתעדכנים אוטומטי
צריך להיות כתוב- הנתונים מתעדכנים באופן אוטומטי

תקנו בבקשה
![2015 03 05 12 47 57](https://cloud.githubusercontent.com/assets/10020924/6503477/212739b2-c336-11e4-93f2-fd35278eb468.png)

@eldadtzadok

**Comment by nir-jackson** [comment]
בוצע
