### ISSUE TITLE
Monthly records of 4 words

### ISSUE THREAD

**Issue by mushon** [shenkarlab/Off-The-record#40]
Why can't we see the monthly records of the 4 words? Is it a bug you're working on or some bigger problem? It already worked before.

**Comment by nir-jackson** [comment]
give me an example please @mushon

**Comment by nir-jackson** [comment]
![image](https://cloud.githubusercontent.com/assets/9511653/6504515/e8b87572-c340-11e4-9988-4ca206eb8962.png)

**Comment by nir-jackson** [comment]
@mushon the only reason it shows nothing is when there is no data. as allways it all depends on the data i receive.

**Comment by shaulams** [comment]
אוקי, זו הפעם הראשונה שבה הבנתי בכלל שאפשר לפתוח את זה. כדאי לשים שם איזה
הסבר, כי אחרת אין שום דרך להבין את זה
ולמה אתם כותבים באנגלית כל הזמן?

**Comment by nir-jackson** [comment]
מושון התחיל חחחח

**Comment by mushon** [comment]
OK, same problem here, only after Shaul wrote it did I remember this + trick. Even I, as someone who've seen it presented in the past forgot where to find it. I expected that clicking the year would open the months. @shenkarlab/off-the-record you need to solve this as this is very user unfriendly. פארדון מיי פרנץ׳

**Comment by shaulams** [comment]
ואם כבר, שמתי לב שהרבה פעמים אם אני לוחץ על מילה בתצוגה הזו, אז כתוב לי שיש
תוצאות, אבל אני לא רואה אותן תמיד. לפעמים כן, לפעמים לא. מצורפים כמה צילומי
מסך לדוגמאות

**Comment by nir-jackson** [comment]
אין תוצאות מלפני 2013 זה מה שיש לכיכר המדינה במאגר מידע

**Comment by mushon** [comment]
@nir-jackson @shaulams  את זה נדסקס באישיו #41

**Comment by moranbz** [comment]
מושון הפתרון של ״ללחוץ על השנה ושהיא תפתח בעייתי, משום שכשלוחצים על שנה מסמנים אותה, כלומר בוחרים בה

**Comment by mushon** [comment]
כן, אני מבין.
אז בואו תשנו את העיצוב של הפלוס
אני חושב שאם הוא יופיע באופן קבוע לצד השנה זה יוכל לעזור
אפילו אם זה לא יהיה פתרון מושלם

**Comment by moranbz** [comment]
סבבה. ניר תוכל לעשות את זה?
שהפלוס יופיע תמיד ולא רק בהובר?

**Comment by mushon** [comment]
אולי עדיף להשתמש בסימן שברון-מטה: ![chevron-down](http://library.owu.edu/images/icon-chevron-down-gray.png)
http://fortawesome.github.io/Font-Awesome/icon/chevron-down/

ולצמצום בשברון-מעלה: ![chevron-down](http://library.owu.edu/images/icon-chevron-up-gray.png)
http://fortawesome.github.io/Font-Awesome/icon/chevron-up/

**Comment by mushon** [comment]
או ב-X לצמצום, לשיקולכם…

**Comment by nir-jackson** [comment]
כרגע זה אובייקט טקסט 
לעשות שתמיד יהיה + זה לא בעיה.

אבל להוסיף תמונה דורש ממני להכין אובייקט חדש שמתנהג כמו הטקסט. זה סיפור ארוך שעלול לקחת כשלוש שעות.

**Comment by nir-jackson** [comment]
אז מה הוחלט? @mushon @moranbz @eldadtzadok

**Comment by eldadtzadok** [comment]
תגידו, לסימן שיש מעל המקש 6 אין חבר הפוך?

**Comment by mushon** [comment]
לא

**Comment by nir-jackson** [comment]
טוב אני עושה שיהיה ליד הכל את הסימן + אלא אם כן תגידו אחרת. אני רוצה להפסיק לעבוד על האתר כבר

**Comment by nir-jackson** [comment]
עשיתי שתמיד יהיה + ליד השנה

**Comment by mushon** [comment]
ok, this is closed
