### ISSUE TITLE
Add close (X) button to the posts lightbox that opens from the search results

### ISSUE THREAD

**Issue by mushon** [shenkarlab/Off-The-record#45]

**Comment by nir-jackson** [comment]
@moranbz 
היה בעבר אבל מורן החליטה להסירו....

**Comment by moranbz** [comment]
אין בעיה שיהיה, אבל שעדיין יהיה אפשר לסגור גם אם לוחצים בצדדים...

**Comment by nir-jackson** [comment]
ברור. אני מוסיף

איך זה נראה?

![image](https://cloud.githubusercontent.com/assets/9511653/6508627/a16b6450-c362-11e4-9ccb-db6a91852d0c.png)

**Comment by moranbz** [comment]
עדיף שיהיה בשורה של ״נמצאו 10 תוצאות״ , אצלי החלק שבו זה נמצא כרגע ממש נחתך מההדר... ואני מניחה שזה קורה בהרבה מחשבים ניידים...
ואם אפשר אז גם שלא יגלל ביחד עם הפוסטים...

**Comment by nir-jackson** [comment]
סידרתי

זה ליד ה״נמצאו 10 תוצאות״

וזה נשאר במקום (לא נגלל)

**Comment by moranbz** [comment]
אלוף אתה!
