### ISSUE TITLE
מתי משיקים את האתר?

### ISSUE THREAD

**Issue by nir-jackson** [shenkarlab/Off-The-record#46]
נכון לעכשיו אני סיימתי לעבוד על האתר.
תעלו בבקשה את מה שיש לשרת ותריצו שוב את הסקריפטים אחרי שמחקתם את הדאטה הקיים.

דברו איתי אחרי שמה שכתבתי באוויר.
@mushon @akariv

**Comment by nir-jackson** [comment]
@mushon @shaulams @akariv 

אני מבקש לפני שאתם פותחים על "בעיה" נוספת שהאתר המעודכן יעלה.
@akariv אולי תגיד לי איך לעשות את זה ואני יעלה כבר את האתר כדי שכולם יוכלו לראות את השינוי שעשיתי?

**Comment by akariv** [comment]
למיטב ידיעתי זה כבר למעלה... תוכל לוודא בבקשה?

**Comment by nir-jackson** [comment]
זה עוד לא עלה.

בבקשה תעלה מחדש את הקבצים 
index.html
Top3.js
Visualization.js
featherlight.css
style_new_new.css

* או שפשוט תעלה את כל תוכן תיקיית WebSite 
מחדש

**Comment by akariv** [comment]
עכשיו עלה - זה לא נראה עובד.

אדם

**Comment by nir-jackson** [comment]
תודה רבה אדם!!!!

@mushon @shaulams 
עכשיו שהאתר עלה תעברו עליו ותתנו הערות 
*כמובן תתחשבו בזה שעבדתי המון כבר על האתר הזה ואני רוצה לקפל עניינים
