### ISSUE TITLE
טעות כתיב

### ISSUE THREAD

**Issue by shaulams** [shenkarlab/Off-The-record#47]
זה לא תוקן
צריך להיות הנתונים מתעדכנים באופן אוטומטי
![2015 03 05 20 17 12](https://cloud.githubusercontent.com/assets/10020924/6511327/bb9ae834-c374-11e4-89e8-67c1740b4184.png)

**Comment by nir-jackson** [comment]
זה תוקן......
@akariv  אדם עדיין לא העלה את כל התיקונים שעשיתי.... אתה עדיין רואה את האתר מלפני התיקונים.

כבר כמה פעמים ביקשתי להעלות את האתר וזה עדיין לא קרה...

**Comment by nir-jackson** [comment]
@shaulams אתה יכול לראות עכשיו שזה תוקן
