### ISSUE TITLE
עמוד אודות בעייתי

### ISSUE THREAD

**Issue by shaulams** [shenkarlab/Off-The-record#48]
כשאני פותח את עמוד האודות נפתח לי קובץ פידיאף נורא נורא כבד, וחוצמזה הוא חתוך משום מה

**Comment by nir-jackson** [comment]
מתעמי זמן החלטנו להכין את דף האודות כקובץ PDF. 
אני מסכים שהוא כבד מידי וצריך למצוא דרך לצמצם את הגודל שלו 
@eldadtzadok

**Comment by moranbz** [comment]
נירוש כמה הוא שוקל כרגע? אני אנסה להקטין

**Comment by shaulams** [comment]
הוא גם חתוך, תשימו לב

**Comment by nir-jackson** [comment]
הוא עכשיו שוקל 8 מגה

**Comment by mushon** [comment]
אני מבין אם אתם לא רוצים לכתוב את ההטמל שלו בשלב הזה אבל אני חושב שקובץ תמונה יהיה עדיף על PDF
תעלו אותו כPNG ותסגרו עניין

**Comment by moranbz** [comment]
בדיוק שלחתי מייל (:
עכשו הפידיאף שוקל
200kb

**Comment by nir-jackson** [comment]
@mushon 
ראיתי ששינת את הקוד בVisualization.js
בכדי לתקן את זה שהכתוב נחתך.
להבא דבר איתי לפני שאתה מעלה קוד מפני שראיתי את הבאג הזה אתמול בלילה וסידרתי 
small fixes #4
אני ראיתי שמחקת את תכונת הwidth
ואת תכונת הmargin-right.
צריך את התכונות האלו (במיוחד ההזחה ימינה) כדי לדאוג שהכל מיושר.
אני מחזיר אחורה לקוד שלי.

**Comment by nir-jackson** [comment]
תיקון, אני אשאיר את שלך.

**Comment by mushon** [comment]
סבבה,
לא רציתי להציק לך עם זה.

בכל מקרה תיקנתי את זה עם ההזכה, פשוט העברתי אותה לאלמנט הפנימי, תראה שזה עובד.
אין צורך ב-90% או ב-100% על האלמנט.

בכל מקרה, סבבה שתיקנת :)
On March 6, 2015 at 10:24:58 AM, Nir Jackson (notifications@github.com) wrote:

@mushon
ראיתי ששינת את הקוד בVisualization.js
בכדי לתקן את זה שהכתוב נחתך.
להבא דבר איתי לפני שאתה מעלה קוד מפני שראיתי את הבאג הזה אתמול בלילה וסידרתי
small fixes #4
אני ראיתי שמחקת את תכונת הwidth
ואת תכונת הmargin-right.
צריך את התכונות האלו (במיוחד ההזחה ימינה) כדי לדאוג שהכל מיושר.
אני מחזיר אחורה לקוד שלי.

**Comment by nir-jackson** [comment]
והעלתי את הPDF החדש לגיט האב
רק צריך להעלות אותו לשרת שיחליף את הישן

**Comment by nir-jackson** [comment]
חשוב לי לציין שאני מעדיף PDF 
מפני שאפשר בלהעתיק טקסט ככה
בתמונה מן הסתם אי אפשר
בכל מקרה אני סוגר את הISSUE הזה
