### ISSUE TITLE
רווח אחרי מילה בגלישה מהמובייל 

### ISSUE THREAD

**Issue by shaulams** [shenkarlab/Off-The-record#50]
אם אני נכנס למערכת מהמובייל ומכניס מילה עם רווח אחריה, כמו שקורה הרבה כשמשתמשים בסוויפטקי, הוא אומר לי שאין תוצאות

**Comment by nir-jackson** [comment]
צודק,
בטעות סידרתי את זה רק בשביל האתר הרגיל.
עכשיו סידרתי את זה גם בשביל המוביל

**Comment by shaulams** [comment]
תודה רבה
