### ISSUE TITLE
דחוף!! - אי אפשר לחפש את המלים שסיננו בשביל מסך השוואת הפוליטיקאים 

### ISSUE THREAD

**Issue by shaulams** [shenkarlab/Off-The-record#53]
שלום לכולם
המערכת באוויר ואנחנו מתחילים לקבל פידבק מגולשים, ולכן חשוב שנטפל בזה בדחיפות

אני מזכיר לכם שסיננו כל מיני מלים בשביל המסך האחרון שמאפשר להשוות בין פוליטיקאים
פתאום מתברר לי שאי אפשר לחפש את המלים הזה במסך החיפוש הראשי
מצרף צילומסך

איך פותרים את זה? חייבים לפתור את זה בהקדם
![2015 03 08 21 30 27](https://cloud.githubusercontent.com/assets/10020924/6547208/5c409330-c5da-11e4-9feb-7eba9eafba11.png)

**Comment by AlexGr2** [comment]
ישראל נמצאת במילים שמערכת לא שומרת, אני לא זכור בדיוק למה, אבל היא נמצאת
ברשימה של avoid words. אין שום בעיה להחזיר אותה, רק שמישהו תזכיר למה היא
נמצאת ברשימה של מילים שאני אמור להתעלם מהם?

2015-03-08 21:30 GMT+02:00 shaulams <notifications@github.com>:

**Comment by nir-jackson** [comment]
אלכס אם זה לא היה ברור התכוונו לסנן את המילים רק מהחלק האחרון (המילים לפי חודש)
זה קריטי שהמילים האלו יהיו בחיפוש!

**Comment by nir-jackson** [comment]
@AlexGr2 אתה מבין מה הבעיה?
אתה יכול לסדר את זה?

**Comment by AlexGr2** [comment]
כן שלחתי לא מעודכן.

**Comment by nir-jackson** [comment]
תוריד את מה שיש כאן בגיטהאב ותעדכן

**Comment by nir-jackson** [comment]
בחיפוש לא צריך לסנן אף מילה לכן אני מרוקן את avoidWords2
סבבה אלכס?

**Comment by AlexGr2** [comment]
אתה בטוח לגבי זה? כבר הורדתי את ישראל ועשיתי commit. עם תרקן את המערך
המילות קשר יצלופו את כל data

**Comment by shaulams** [comment]
רק שלא נפיל את כל האתר או משהו כזה

**Comment by nir-jackson** [comment]
אני בטוח בחיפוש אמורים לראות את כל התוצאות. סינון המילים נועד רק בשביל החלק האחרון לראות תוצאות מעניינות.
הדבר היחידי שצריך להשאר שם זה כל סימני הפיסוק (דברים שאינם מילים(

**Comment by AlexGr2** [comment]
אם זה משהו שצריך אז סבבה, הורדת כבר? או שאני מוריד

2015-03-08 23:34 GMT+02:00 Nir Jackson <notifications@github.com>:

**Comment by nir-jackson** [comment]
תוריד בבקשה

**Comment by AlexGr2** [comment]
שמתי

**Comment by nir-jackson** [comment]
תודה רבה!
@akariv 
אהלן אדם.
עדכנו את הסקריפט MainScript.py
אני צריך שתעדכן אותו ותריץ אותו מחדש. 
לא צריך למחוק את המידע הישן

**Comment by nir-jackson** [comment]
@shaulams 
איפה שמתם את הקישור לאתר?

**Comment by AlexGr2** [comment]
הייתי ממליץ לנקות את הדאטא הקודמת כדי שלא יהיו בעיות כמו שהם צצים, וגם צריך
להריץ threeLetterListGather.py אחרי סיום

**Comment by shaulams** [comment]
הנה הקישור לאתר
http://www.calcalist.co.il/local/articles/0,7340,L-3653978,00.html

מחר זה יקודם הרבה יותר אגרסיבית  (וכבר הערב צבר תאוצה יפה דרך פייסבוק). 
נשאלת השאלה - הכנסתם קוד של אנליטיקס פנימה? שנדע לקבל אנליטיקות?
אם לא, כדאי לעשות את זה הלילה בהנחה שזה לא מסובך מדי, כי מחר בבוקר זה יתחיל להיות מקודם דרך וואינט, מה שאומר שיתחילו להיכנס עשרות אלפי אנשים

@nir-jackson

**Comment by nir-jackson** [comment]
לא הכנסתי,
אני גם לא כלכך מכיר איך להכניס וכמה זמן זה יכול לקחת.
אני אבדוק את זה.
@akariv 
אדם מה אתה אומר?

**Comment by akariv** [comment]
הכנסתי.

**Comment by nir-jackson** [comment]
@akariv 
תודה רבה! עדכנת כבר את המידע?

@shaulams אני ראיתי את דף הפייסבוק שלך
לגבי ה"אני" זה גם יתוקן עם העדכון האחרון.

**Comment by akariv** [comment]
אמור להיות מעודכן (ואם לא - אז בעוד שעתיים בטוח).

אדם

**Comment by nir-jackson** [comment]
אני סוגר את הבעיה מפני שהיא נפתרה
