### ISSUE TITLE
במובייל אין ספירה של מספר התוצאות

### ISSUE THREAD

**Issue by shaulams** [shenkarlab/Off-The-record#54]
בגרסת המובייל המספר הקטן בעיגול הכחול לא מציין את מספר התוצאות אלא את המיקום בדירוג
ראו צילומסך
![b_mxkqbuwaan8fh](https://cloud.githubusercontent.com/assets/10020924/6547295/b62c9c66-c5dc-11e4-9b7c-0c9bf4a153ff.jpg)

**Comment by nir-jackson** [comment]
בטיפול,
אעדכן כשזה עובד

**Comment by shaulams** [comment]
תודה

**Comment by nir-jackson** [comment]
עדכנתי את הקובץ
Visualization.js
@akariv 
אתה יכול להעלות אותו בבקשה?

**Comment by akariv** [comment]
העליתי
