### ISSUE TITLE
עוד פוליטיקאים כפולים!

### ISSUE THREAD

**Issue by shaulams** [shenkarlab/Off-The-record#55]
במובייל, זהבה גלאון ודב חנין כפולים משום מה
![2015 03 08 22 33 40](https://cloud.githubusercontent.com/assets/10020924/6547538/43852d2a-c5e3-11e4-8d47-20e62e7ed62d.png)

**Comment by nir-jackson** [comment]
אני לא מצליח לשחזר את הבעיה...
לי הם לא הופיעו כפול.
תנסה לרענון ולהגיד לי אם זה קורה שוב

**Comment by nir-jackson** [comment]
זה קרה לך שוב? יש תלונות ממשתמשים שזה קורה להם?

**Comment by shaulams** [comment]
לא

**Comment by nir-jackson** [comment]
מעולה טוב לשמוע.
שאול אני זמין בכל רגע. אם יש משהו קריטי אל תהסס להתקשר
0525566001
