### ISSUE TITLE
תלונת משתמשים - תוצאות מוזרות

### ISSUE THREAD

**Issue by shaulams** [shenkarlab/Off-The-record#56]
בוקר טוב
אני משתף אתכם בתלונה של כמה משתמשים
בחיפוש המילה - סלולר - כחלון בכלל לא מופיע בתוצאות
האמת שזה די מוזר. מצורף צילומסך
איך זה יכול להיות?
![2015 03 09 08 58 59](https://cloud.githubusercontent.com/assets/10020924/6551059/a5f2c9a2-c63a-11e4-8ee7-79aa271c0011.png)

**Comment by AlexGr2** [comment]
אצלי הוא מופיעה

**Comment by AlexGr2** [comment]
[image: Inline image 2]

2015-03-09 9:27 GMT+02:00 Alex Grushevich <grushkoa1@gmail.com>:

> אצלי הוא מופיעה
>

**Comment by AlexGr2** [comment]
ושאול, אל תשכח שבשביל להכניס את כחלון הורדנו רף מינימלי של 50k מילים ל 35k
כי הוא אפילו לא במחצית הראשונה.

2015-03-09 9:29 GMT+02:00 Alex Grushevich <grushkoa1@gmail.com>:

> [image: Inline image 2]
>
> 2015-03-09 9:27 GMT+02:00 Alex Grushevich <grushkoa1@gmail.com>:
>
>> אצלי הוא מופיעה
>>
>
>

**Comment by nir-jackson** [comment]
דבר ראשון אלכס הורדנו את הרף ל35,000
לא 50 אלף.
דבר שני. זה אמור להשפיע רק על העמוד הראשון!
כמו במקרה הקודם בחיפוש ובדף האחרון כחום אמורים להופיע

הסיבה שהוא לא מופיע בחיפוש המילה "סלולר" זה בגלל שהוא באמת לא רשם אותה.
עברתי ידנית על כל העמוד שלו ומצאתי 4 תזכורים של המילה.
פעמיים "הסלולר" ופעמיים "בסלולר" זה המצב....

**Comment by AlexGr2** [comment]
זה בדיוק על מה שדברתי שהיה לנו רף של 50000 והרדנו אותו ל35000 כדי להכניס את
כחלון, תקרא עוד פעם את המייל שלי. וזה משפיעה רק על עמוד הראשון איפה שיש על
הטפטים הזזים. ציינתי את זה רק להבהיר שעוד אין לו אוצר מילים גדול בפייסבוק.

2015-03-09 9:44 GMT+02:00 Nir Jackson <notifications@github.com>:

**Comment by nir-jackson** [comment]
בסדר גמור :smile:

**Comment by shaulams** [comment]
הבנתי. תודה רבה, אפשר לסגור את זה
